CREATE TABLE paper_trading_logs (
    signal_id TEXT PRIMARY KEY,
    experiment_id TEXT,
    feature_version TEXT,
    date TEXT,
    symbol TEXT,
    model_version TEXT,
    target_days INTEGER,
    threshold REAL,
    prob_threshold REAL,
    p_buy REAL,
    p_hold REAL,
    p_sell REAL,
    expected_return REAL,
    expected_edge REAL,
    market_regime TEXT,
    stock_regime TEXT,
    signal_quality TEXT,
    suggested_position REAL,
    position_risk REAL,
    price_t REAL,
    entry_price_t1 REAL,
    actual_price_t3 REAL,
    actual_return_t3 REAL,
    prediction_error REAL,
    data_timestamp TEXT,
    prediction_timestamp TEXT,
    execution_timestamp TEXT,
    status TEXT DEFAULT 'T0_LOGGED'
);
